# Generated by Django 2.0.5 on 2018-09-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect', models.CharField(choices=[('A', 'First'), ('B', 'Second'), ('C', 'Third')], default='A', max_length=30)),
            ],
        ),
    ]
